[workspace]
members = ["node", "pallets/template", "runtime"]
package.edition = "2021"
package.repository = "https://github.com/paritytech/polkadot-sdk"
resolver = "2"

[profile.release]
panic = "unwind"
