[package]
name = "fhe-precompile"
authors = { workspace = true }
description = "Precompile for FHE"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = "0.1.0"

[dependencies]
pallet-fhe = { path = "../pallet", default-features = false }
fhe-primitives = { path = "../primitives", default-features = false }

fp-evm = { workspace = true }
pallet-evm = { workspace = true }
evm = { version = "1.0.0", default-features = false }

parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-std = { workspace = true }

tfhe = { version = "1.0.0", default-features = false, features = ["boolean", "shortint", "integer"] }

[features]
default = [ "std" ]
std = [
    "fp-evm/std",
    "pallet-fhe/std",
    "pallet-evm/std",
	"parity-scale-codec/std",
    "scale-info/std",
    "sp-core/std",
    "sp-io/std",
	"sp-std/std",
]